title: Joe Guan's Website
author: Joe Guan
email: jguan@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is a test website that was created for my AP Computer Science A course. 

# social links
twitter_username: JoeGuan17 # DO NOT include the @ character, or else the build will fail!
github_username:  JoeGuan552 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
